---
title: "Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(rsconnect)
library(shiny)
```

```{r include=FALSE}
# Directories
final = read_csv("./data/HIV_AIDS_Diagnoses_by_Neighborhood__Sex__and_Race_Ethnicity.csv")

final_location = read_csv("./data/HIV_Testing_Locations.csv")
```


```{r include=FALSE}
## dropping last column because it is empty
n_to_b = read_csv("./data/Manhattan_Neighborhood_to_Borough.csv")[,-6]

n_to_b = n_to_b %>% 
  pivot_longer(Brooklyn:`Staten Island`, names_to = "borough", values_to = "neighborhood") %>%
  na.omit()

final = final %>% janitor::clean_names()

extract_nbh = function(x){
  # split the string by "-"
  splited = unlist(strsplit(x, "-"))
  if (length(splited) > 1){
    # get the last string because it contains the actual address
    last = tail(splited, n=1)
    if (last == " Murray Hill"){
      return(substr(splited[1], 1, 8))
    }
    # obmit the space at the begining
    return(substr(last, 2, nchar(last)))
  } else{
    return(splited)
  }
}

final = final %>%
  mutate(neighborhood = unlist(map(neighborhood_u_h_f, extract_nbh)))

final = left_join(final, n_to_b, by="neighborhood")

```


```{r include=FALSE}
final[which(final$neighborhood == "Southeast Queens"),]$borough = "Queens"
final[which(final$neighborhood == "Southwest Queens"),]$borough = "Queens"
final[which(final$neighborhood == "West Queens"),]$borough = "Queens"
final[which(final$neighborhood == "Rockaway"),]$borough = "Queens"
final[which(final$neighborhood == "Upper Westside"),]$borough = "Manhattan"
final[which(final$neighborhood == "Upper Eastside"),]$borough = "Manhattan"
final[which(final$neighborhood == "Lower Eastside"),]$borough = "Manhattan"
final[which(final$neighborhood == "Lower Manhattan"),]$borough = "Manhattan"
final[which(final$neighborhood == "Bronx Park"),]$borough = "Bronx"
final[which(final$neighborhood == "Tremont"),]$borough = "Bronx"
final[which(final$neighborhood == "Northeast Bronx"),]$borough = "Bronx"
final[is.na(final$borough),]
```

```{r include=FALSE}
final = na.omit(final)

final = final %>%
  mutate(total_number_of_concurrent_hiv_aids_diagnoses = as.numeric(total_number_of_concurrent_hiv_aids_diagnoses),
         total_number_of_aids_diagnoses = as.numeric(total_number_of_aids_diagnoses),
         total_number_of_hiv_diagnoses = as.numeric(total_number_of_hiv_diagnoses),
         aids_diagnoses_per_100_000_population = as.numeric(aids_diagnoses_per_100_000_population),
         hiv_diagnoses_per_100_000_population = as.numeric(hiv_diagnoses_per_100_000_population)) %>%
  mutate(total_number_of_concurrent_hiv_aids_diagnoses = replace_na(total_number_of_concurrent_hiv_aids_diagnoses, 0),
         total_number_of_aids_diagnoses = replace_na(total_number_of_aids_diagnoses, 0),
         total_number_of_hiv_diagnoses = replace_na(total_number_of_hiv_diagnoses, 0),
         aids_diagnoses_per_100_000_population = replace_na(aids_diagnoses_per_100_000_population,0),
         hiv_diagnoses_per_100_000_population = replace_na(hiv_diagnoses_per_100_000_population,0),
         proportion_of_concurrent_hiv_aids_diagnoses_among_all_hiv_diagnoses = as.numeric(proportion_of_concurrent_hiv_aids_diagnoses_among_all_hiv_diagnoses)) %>%
mutate(total_number_of_aids_diagnoses   = as.numeric(total_number_of_aids_diagnoses  )) %>%
mutate(aids_diagnoses_per_100_000_population  = as.numeric(aids_diagnoses_per_100_000_population))
  
skimr::skim(final)
```


```{r, warning=TRUE, include=FALSE}
borough_final = final %>% 
  select(- neighborhood_u_h_f, -neighborhood) %>% 
  mutate_if(is.character, str_to_lower) %>% 
  group_by(borough, year, sex, race_ethnicity) %>% 
  summarise(
    total_hiv_diagnosis = sum(total_number_of_hiv_diagnoses, na.rm = TRUE),
    total_number_of_concurrent_hiv_aids_diagnoses = sum(total_number_of_concurrent_hiv_aids_diagnoses, na.rm = TRUE),
    total_number_of_aids_diagnosis = sum(total_number_of_aids_diagnoses, na.rm = TRUE),
    hiv_diagnoses_per_100_000_population = mean(hiv_diagnoses_per_100_000_population, na.rm = TRUE),
    proportion_of_concurrent_hiv_aids_diagnoses_among_all_hiv_diagnoses = mean(proportion_of_concurrent_hiv_aids_diagnoses_among_all_hiv_diagnoses, na.rm = TRUE),
    aids_diagnoses_per_100_000_population = mean(aids_diagnoses_per_100_000_population, na.rm = TRUE)
  ) 
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}

boros = borough_final %>% pull(borough) %>% unique() 
# selectInput widget
checkboxGroupInput("borough_choice", label = h5("Select borough"), choices = boros, selected = boros)

race = borough_final %>% pull(race_ethnicity) %>% unique()
checkboxGroupInput("race_choice", label = h5("Select Race"), choices = race, selected = race)

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Trend of HIV diagnosis over the years through years 2010 to 2013

```{r}

renderPlotly({ 
  borough_final %>%
  ungroup() %>% 
  filter(borough == input$borough_choice) %>% 
  group_by(year, sex) %>% 
  ggplot(aes(x = year, y = total_hiv_diagnosis)) + 
  geom_col(aes(fill = sex), position = "dodge") +
  theme(legend.position = "bottom")
})

```

### Trend of AIDS diagnosis over the years through years 2010 to 2013

```{r}

renderPlotly({ 
  borough_final %>%
  ungroup() %>% 
  filter(borough == input$borough_choice) %>% 
  group_by(year, sex) %>% 
  ggplot(aes(x = year, y = total_number_of_aids_diagnosis)) + 
  geom_col(aes(fill = sex), position = "dodge") +
  theme(legend.position = "bottom")
})


```

### Trend of concurrent HIV & AIDS diagnosis over the years through years 2010 to 2013

```{r}

renderPlotly({ 
  borough_final %>%
  ungroup() %>% 
  filter(borough == input$borough_choice) %>% 
  group_by(year, sex) %>% 
  ggplot(aes(x = year, y = total_number_of_concurrent_hiv_aids_diagnoses)) + 
  geom_col(aes(fill = sex), position = "dodge") +
  theme(legend.position = "bottom")
})

```
  
Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### Proportion of HIV cases by race
 

```{r}

renderPlotly({ 
  borough_final %>%
  ungroup() %>% 
  filter(race_ethnicity == input$race_choice) %>% 
  group_by(year, race_ethnicity) %>% 
  ggplot(aes(x = year, y = hiv_diagnoses_per_100_000_population)) + 
  geom_col(aes(fill = sex), position = "dodge") +
  theme(legend.position = "bottom")
})

```

### Proportion of AIDS cases by race


```{r}

renderPlotly({ 
  borough_final %>%
  ungroup() %>% 
  filter(race_ethnicity == input$race_choice) %>% 
  group_by(year, race_ethnicity) %>% 
  ggplot(aes(x = year, y = aids_diagnoses_per_100_000_population)) + 
  geom_col(aes(fill = sex), position = "dodge") +
  theme(legend.position = "bottom")
})

```

### Proportion of HIV and AIDS cases by race

```{r}

renderPlotly({ 
  borough_final %>%
  ungroup() %>% 
  filter(race_ethnicity == input$race_choice) %>% 
  group_by(year, race_ethnicity) %>% 
  ggplot(aes(x = year, y = proportion_of_concurrent_hiv_aids_diagnoses_among_all_hiv_diagnoses)) + 
  geom_col(aes(fill = sex), position = "dodge") +
  theme(legend.position = "bottom")
})

```

